name: 'publish'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Gitbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: tuliren/publish-gitbook@v1.0.0
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
